### ISSUE TITLE
Quando se muda do menu management para o execution ou vice versa, o campo do lado direito do ecrã não muda. Acho preferível mudar.

### ISSUE THREAD

**Issue by pedroaugustomartins** [pedro-borges/psyNote#56]

**Comment by pedro-borges** [comment]
Isto já estava reportado e fechado. Actualiza a aplicacao

**Comment by pedroaugustomartins** [comment]
Ok! Está a funcionar bem!

No dia sexta-feira, 24 de abril de 2015, Pedro Borges <
notifications@github.com> escreveu:
